### ISSUE TITLE
Question about the KG dataset

### ISSUE THREAD

**Issue by LEOXC1571** [zjukg/LPKG#1]
The huggingface repo (WJJ-ZJU/CLQA_Wiki) is not available, is the dataset the same with the 'CLQA-Wiki/CLQA_Wiki_v1.json'? Thank you for your attention.

**Comment by wjj0122** [comment]
We update the huggingface repo now, you can get our datasets from https://huggingface.co/datasets/zjukg/LPKG

**Comment by bernaljg** [comment]
Hi, thanks so much for making the dataset available! 

I wanted to clarify something. Is there a guarantee that there are files in the Wikipedia dump that provide answers to all the questions in CLQA-Wiki?
